# Welcome to Serverless!
service: serverless-example
app: assignment-api


provider:
  name: aws
  runtime: nodejs12
  stage: dev
  region: us-east-1


functions:
  assignmentAPI:
    handler: src/controller/assignment.handler
    events:
        - http:
            path: /index
            method: get


        - http:
            path: /
            method: post


        - http:
            path: /
            method: get

        - http:
            path: /{productId}
            method: get


plugins:
  - serverless-offline
  - serverless-dotenv-plugin
